# Generated by Django 5.1.2 on 2024-10-20 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
