# Generated by Django 5.1.2 on 2024-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
    ]
