# Generated by Django 5.1.2 on 2024-10-21 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_comment_meal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='created_at',
            new_name='data',
        ),
    ]
