# Generated by Django 5.1.2 on 2024-10-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_rename_data_meal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='date',
            new_name='created_at',
        ),
    ]
