# Generated by Django 5.1.2 on 2024-10-16 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="min_participants",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="post",
            name="click",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.CreateModel(
            name="JoinRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_comfirmed", models.BooleanField(default=False)),
                ("is_denied", models.BooleanField(default=False)),
                ("is_valid", models.BooleanField(default=False)),
                (
                    "target_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_group_request",
                        to="forum.grouppost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
