# Generated by Django 5.1.2 on 2024-10-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_grouppost_min_participants_alter_post_click_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="address",
            field=models.CharField(default="默认", max_length=40),
        ),
    ]
