# Generated by Django 5.1.2 on 2024-10-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_grouppost_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="forum",
            name="notice",
            field=models.TextField(null=True),
        ),
    ]
