# Generated by Django 5.1.2 on 2024-10-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_forum_description_alter_forum_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="forum",
            name="notice",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="imaged",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
