# Generated by Django 5.1.2 on 2024-10-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0006_post_forum_alter_post_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
