# Generated by Django 5.1.2 on 2024-10-18 13:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_post_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.FileField(upload_to="illustrations/")),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="imaged",
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="post_images", to="forum.postimage"
            ),
        ),
    ]
