# Generated by Django 5.1.2 on 2024-10-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0009_alter_grouppost_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
