# Generated by Django 5.1.2 on 2024-10-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_alter_grouppost_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="state",
            field=models.IntegerField(default=0),
        ),
    ]
