# Generated by Django 5.1.2 on 2024-10-19 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0012_joinrequest_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="last_modified",
            field=models.DateField(auto_now=True),
        ),
    ]
