# Generated by Django 5.1.2 on 2024-10-19 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0013_joinrequest_create_at_joinrequest_last_modified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="joinrequest",
            constraint=models.UniqueConstraint(
                fields=("user", "target_post"), name="unique_user_targetpost"
            ),
        ),
    ]
