# Generated by Django 5.1.2 on 2024-10-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0016_rename_is_comfirmed_joinrequest_is_confirmed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
